Shoulderfixes
ligerbots/InfiniteRecharge2021 pull request #46
Opened 2021-02-22 01:04 UTC by YJ-7274

2021-02-22 01:46 UTC, prensing requested changes
I suspect most of the class instance variables in Climber can be deleted.

2021-02-22 01:47 UTC, prensing commented
This change must have been branched of plotTrajectory, which is not "right", but also not a problem.

2021-02-22 01:57 UTC, prensing requested changes

2021-02-22 01:57 UTC, prensing commented on src/main/java/frc/robot/commands/DeployIntake.java
> +      this.climber = climber;
Please fix the indentation

2021-02-22 01:57 UTC, prensing commented on src/main/java/frc/robot/commands/DeployIntake.java
> +    climber.shoulder.setIdleMode(IdleMode.kBrake);
"started" should be set to false in initialize().

2021-02-22 01:57 UTC, prensing commented on src/main/java/frc/robot/commands/DeployIntake.java
> +    started = true;
This should be inside the above if() block. No need to set it every time.

2021-02-22 01:57 UTC, prensing commented on src/main/java/frc/robot/commands/DeployIntake.java
> +      climber.shoulder.setVoltage(0.3);
This is the "hold" voltage, which is not what you want. We need a voltage to raise the shoulder just a little.
Make sure to create a "final static" above to hold the value, and give it a good name.

2021-02-22 01:57 UTC, prensing commented on src/main/java/frc/robot/commands/DeployIntake.java
> +      climber.shoulder.setVoltage(-0.1);
The "-0.1" should be put in the class as a "static final" with a good name.

2021-02-22 01:57 UTC, prensing commented on src/main/java/frc/robot/commands/DeployIntake.java
> +    climber.shoulder.setVoltage(Constants.SHOULDER_SPEED_HOLD);
This is no longer needed. Was just for testing.

2021-02-22 01:57 UTC, prensing commented on src/main/java/frc/robot/commands/DeployIntake.java
> +      climber.shoulder.setVoltage(-0.1);
The first loop will not actually work. You will set the voltage (currently 0.3), set start, and then immediately set voltage to -0.1.

2021-02-22 16:08 UTC, YJ-7274 commented
I addressed those changes ;)

2021-02-22 22:34 UTC, prensing commented
YJ the code is looking decent, but somehow along the way, a bunch of changes got lost. The code from the shed was this:
https://github.com/ligerbots/InfiniteRecharge2021/commit/0be780148a468fd734e2d65dca9325334a46f1bd#diff-1000d31648c1ff8b42b5deec3bee8047af990c42a3ff199d5ed9423a8046aaf3

There were a few changes that were undone:
* Climber.shoulderBelowHeight was removed
* there are 3 voltages need: 
    - raise shoulder a little  (you have 0.5;  good starting guess)
    - lower shoulder quickly  (-3.0)
    - near bottom, lower shoulder slowly (-0.3)

2021-02-23 03:10 UTC, prensing approved these changes

2021-02-23 03:29 UTC, prensing commented
Might need tuning of the initial raise of the shoulder, but good for now.

2021-02-23 03:30 UTC, merged